### ISSUE TITLE
What does "Cloud Web Risk is not yet publicly available" in your docs refer to?

### ISSUE THREAD

**Issue by DarraghDuffy** [googleapis/google-cloud-php-web-risk#5]
Hey Folks,

in your docs[1] as part of the installation first paragraph you say :  

_"Cloud Web Risk is not yet publicly available. You must be whitelisted in order to gain access"_

I am not exactly sure what you are saying here. We are planning on implementing Web Risk into a commercial product and I just need clarification on what this comment means. Our product is hosted in AWS (😃) rather than Google Cloud. We have the API working from a simple CLI cURL. Can you clarify this point so that we wont run into issues down the line.

thank You.

[1] Installation Heading
https://github.com/googleapis/google-cloud-php-web-risk

**Comment by dwsupplee** [comment]
Hi @DarraghDuffy, I've opened https://github.com/googleapis/google-cloud-php/pull/4318 to address this as that verbiage is old. Sorry for the confusion!

**Comment by DarraghDuffy** [comment]
Excellent thanks @dwsupplee for the clarification - at least you know we do read documentation 😄
